package org.lab5.communication.requests;

public enum RequestType {
    LOGIN, SET_TRANSPORT_PROTOCOL, LOGOUT, CLIENTS_LIST_REQUEST, CLIENTS_LIST_RECEIVE,
    MESSAGE_FROM_CLIENT, MESSAGE_FROM_SERVER, MESSAGE_LIST, NOTIFICATION
}
